Lab 3 golang function
ISUCT/Informatics_2023 pull request #120
Opened 2023-10-27 19:32 UTC by holenyt

2023-11-12 08:50 UTC, jskonst requested changes

2023-11-12 08:50 UTC, jskonst commented on golang/main.go
> +const x_delta float64 = 0.8
не надо глобальных переменных

2023-11-12 08:50 UTC, jskonst commented on golang/main.go
> +	}
выносите в отдельную функцию

2023-11-13 17:01 UTC, holenyt commented on golang/main.go
> +	}
Записывать в срез полученные результаты?

2023-11-18 08:31 UTC, jskonst requested changes

2023-11-18 08:31 UTC, jskonst commented on golang/main.go
> +	}
да и в отдельную функцию и в отдельный пакет переносите

2023-11-18 10:25 UTC, holenyt commented
Добавил изменения .-.

2023-11-18 16:12 UTC, jskonst commented on golang/internal/sample.go
> +	var otvet_a = []float64{}
посчитайте сколько должно быть элементов и используйте make с указанием числа элементов, чтобы сократить число операций по пересозданию массива внутри среза

2023-11-18 16:13 UTC, jskonst requested changes

2023-11-18 16:13 UTC, jskonst commented on golang/internal/sample.go
> +	var otvet_b = []float64{}
аналогично используйте make

2023-11-25 09:38 UTC, holenyt commented
Тесты обязательно писать?

2023-11-25 16:21 UTC, jskonst approved these changes

2023-11-25 16:21 UTC, jskonst commented on golang/internal/sample.go
> +	var otvet_a = make([]float64, 0, 6)
ок: но почему 6 ? вы же можете вычислять относительно x_start, x_end, x_delta

2023-11-25 16:21 UTC, merged

2023-11-26 12:14 UTC, holenyt commented on golang/internal/sample.go
> +	var otvet_a = make([]float64, 0, 6)
Потому что, у меня в цикле условие `i <= x_end`, а не `i < x_end`