Lab1 + Lab2
ISUCT/Informatics_2023 pull request #125
Opened 2023-10-31 16:55 UTC by GRUGOLL

2023-11-11 09:41 UTC, jskonst requested changes

2023-11-11 09:41 UTC, jskonst commented on golang/main.go
> +	fmt.Println("Кочетов Максим Романович")
не должно быть 2х main

2023-11-28 05:00 UTC, GRUGOLL commented on golang/main.go
> +	fmt.Println("Кочетов Максим Романович")
Подскажите пожалуйста почему не видит файл main.go при запуске

2023-12-01 21:21 UTC, jskonst requested changes

2023-12-01 21:21 UTC, jskonst commented on golang/internal/lab4/lab4.go
> +	list_answers := make([]float64, 0)
укажите длину нижележащего массива - ее вы можете посчитать (x_end-x_beg)/x_stp + 1

2023-12-01 21:21 UTC, jskonst commented on golang/internal/lab4/lab4.go
> +	list_answers := make([]float64, 0)
а тут еще проще получить длину - len(xList)

2023-12-08 19:34 UTC, jskonst approved these changes

2023-12-08 19:34 UTC, merged