lab_3
ISUCT/Informatics_2023 pull request #127
Opened 2023-11-02 18:59 UTC by RenatZhappuev

2023-11-11 09:24 UTC, jskonst requested changes

2023-11-11 09:24 UTC, jskonst commented on golang/main.go
> +	var deltax float64 = 0.3
a,b, и delta передавайте в виде параметров метода

2023-11-11 09:24 UTC, jskonst commented on golang/main.go
> +	var znachX = []float64{x1, x2, x3, x4, x5}
тут аналогично передавайте параметры

2023-11-11 09:28 UTC, RenatZhappuev commented on golang/main.go
> +	var deltax float64 = 0.3
а внутри функции нужно создавать переменные a1 = a, b1 =b и т.д?

2023-11-11 09:53 UTC, RenatZhappuev commented on golang/main.go
> +	var deltax float64 = 0.3
Исправил, проверьте пожалуйста

2023-11-12 08:42 UTC, jskonst commented on golang/main.go
> +	fmt.Println(answersB)
не выводите а возвращайте значения

2023-11-12 08:43 UTC, jskonst requested changes

2023-11-12 08:43 UTC, jskonst commented on golang/main.go
> +	var znachX = []float64{x1, x2, x3, x4, x5}
сразу передавайте срез (можно конечно еще неопределенное количество параметров)

2023-12-01 21:28 UTC, jskonst requested changes

2023-12-01 21:28 UTC, jskonst commented on golang/internal/lab3/task1&2.go
> +	var answersA []float64 = make([]float64, 0)
посчитайте требуемую длину массива под срез - (x2-x1)/delta +1

2023-12-01 21:28 UTC, jskonst commented on golang/internal/lab3/task1&2.go
> +	var answersB = []float64{}
а тут еще проще - len(znachx)

2023-12-01 21:28 UTC, jskonst commented on golang/internal/lab3/task1&2.go
> +func Task2(a float64, b float64, znachx[5] float64) []float64{
```suggestion
func Task2(a float64, b float64, znachx[] float64) []float64{
```
передавайте срез - тогда можно будет посчитать большее число элементов

2023-12-01 21:28 UTC, jskonst commented on golang/internal/lab5/lab5.go
> +package lab5
откатывайте этот файл пока не зайдет задача с функциями

2023-12-01 21:28 UTC, jskonst commented on golang/internal/lab5/lab5.go
> +}
вот не надо тут такую функцию делать - точне не в этом пакете

2023-12-01 21:28 UTC, jskonst commented on golang/internal/lab5/lab5.go
> +	return Bun{
скажу как и остальным у кого почти 1 в 1 PR - вызовите SetWeight(weight int) в этой функции - иначе вы можете через NewBun (кстати кто такой Bun? bunny? потому как Bun похоже что булочка) создать с отричательным весом например

2023-12-02 07:39 UTC, jskonst requested changes

2023-12-02 07:39 UTC, jskonst commented on golang/internal/lab3/task1&2.go
> +		var y float64 = (math.Pow(b, 3) + math.Pow(math.Sin(a*x), 2)) / (math.Acos(x*b*x) + math.Exp(-x/2))
а у вас функция дублируется на 8 и на 18 строке - выносите в отдельную функцию

2023-12-09 12:10 UTC, jskonst approved these changes

2023-12-09 12:10 UTC, merged