Лаба 3
ISUCT/Informatics_2023 pull request #128
Opened 2023-11-02 19:15 UTC by l3fo

2023-12-01 21:31 UTC, jskonst commented
У вас конфликты на ветке - надо починить

2023-12-01 21:41 UTC, jskonst requested changes

2023-12-01 21:41 UTC, jskonst commented on golang/internal/LAB4/LAB4.go
> +	var a float64 = -2.5
вынесите значение a в параметры функции

2023-12-01 21:41 UTC, jskonst commented on golang/internal/LAB4/LAB4.go
> +	var b float64 = 3.4
вынестите а и b в параметры функции

2023-12-01 21:41 UTC, jskonst commented on golang/internal/LAB4/LAB4.go
> +	x := []float64{}
используйте make для выделения массива нужного размера

2023-12-01 21:41 UTC, jskonst commented on golang/internal/LAB4/LAB4.go
> +		return (0)
а у вас тут разве не должна быть другая формула?

2023-12-01 21:49 UTC, jskonst commented
У вас тут конфликты - надо порешать

2023-12-02 07:47 UTC, jskonst commented
Почините конфликт, а то придется закрыть :)

2023-12-02 07:47 UTC, jskonst commented on golang/internal/LAB4/LAB4.go
> +		return (0)
вопрос все еще актуален

2023-12-02 07:51 UTC, jskonst requested changes

2023-12-02 07:51 UTC, jskonst commented on golang/internal/LAB4/LAB4.go
> +	x := []float64{}
тут тоже надо make использовать

2023-12-02 07:52 UTC, jskonst commented
Но самое главное - конфликт

2023-12-08 19:38 UTC, jskonst requested changes

2023-12-08 19:38 UTC, jskonst commented on golang/internal/LAB4/LAB4.go
> +		return (0)
вопрос все еще актуальнейший - вы хоть ответьте - а то возьму и удалю PR ...

2023-12-08 20:03 UTC, l3fo commented on golang/internal/LAB4/LAB4.go
> +		return (0)
Здравствуйте, вроде формула правильная, в 5 варианте система, или её по другому нужно оформить?

2023-12-09 11:59 UTC, jskonst approved these changes

2023-12-09 11:59 UTC, merged