Lab3ErrorCorrectionLint
ISUCT/Informatics_2023 pull request #135
Opened 2023-11-04 15:16 UTC by UMBRELLA909

2023-11-11 07:52 UTC, jskonst requested changes

2023-11-11 07:52 UTC, jskonst commented on golang/main.go
> +var x5 float64 = 4.52
сразу нет - это глобальные переменные, 
![изображение](https://github.com/ISUCT/Informatics_2023/assets/970835/fb1ab8fd-0a63-4d9d-9f7d-c5ba5faa0f9c)

2023-11-11 07:53 UTC, Greenprize commented on golang/main.go
> +var x5 float64 = 4.52
![image](https://github.com/ISUCT/Informatics_2023/assets/71152598/e0288612-6e1d-4440-baf2-e2660696c027)

2023-11-11 07:53 UTC, jskonst commented on golang/main.go
> +	peremennie := [5]float64{x1, x2, x3, x4, x5}
вот этот массив стоит передавать в виде параметра функции

2023-11-12 17:58 UTC, jskonst requested changes

2023-11-12 17:58 UTC, jskonst commented on golang/main.go
> +	peremennie := [5]float64{x1, x2, x3, x4, x5}
вот это не поправили - или сразу передавайте сюда срез или используйте возможность передать любое количество параметров

2023-11-12 17:58 UTC, jskonst commented on golang/main.go
> +		var y float64 = (math.Log10(math.Pow(x, 3)-1) / (math.Log2(a*math.Pow(x, 2)-b) / math.Log2(5)))
вычисления также вынесите в отдельную функцию

2023-11-12 17:58 UTC, jskonst commented on golang/main.go
> +		var deltaX float64 = 0.2
вот это переносите в отдельную функцию

2023-11-12 17:58 UTC, jskonst commented on golang/main.go
> +func task2(x1 float64, x2 float64, x3 float64, x4 float64, x5 float64) {
функции должны возврашать значения

2023-11-12 17:58 UTC, jskonst commented on golang/main.go
> +		fmt.Println("ResultsOfTask2:" + fmt.Sprint(y))
функция возвращает значения, но не выводит на экран

2023-12-01 22:11 UTC, jskonst requested changes

2023-12-01 22:11 UTC, jskonst commented on golang/internal/lab4.go
> +}
а почему так? тут надо как раз для всех точек посчитать

2023-12-01 22:11 UTC, jskonst commented on golang/main.go
> +	}
вот это как раз надо выносить в отдельную функцию

2023-12-01 22:11 UTC, jskonst commented on golang/main.go
> +	}
и вот это тоже в отдельную функцию

2023-12-02 20:20 UTC, UMBRELLA909 commented
Лабораторная работа №5 готова и ждет своего коммита после подтверждения предыдущей лабораторной работы

2023-12-08 19:39 UTC, jskonst requested changes

2023-12-08 19:39 UTC, jskonst commented on golang/internal/lab4/lab4.go
> +	sliceForTask1 := make([]float64, 0)
посчитайте число элементов - в дискорде даже писал пример как надо с типовой ошибкой

2023-12-09 12:07 UTC, jskonst approved these changes

2023-12-09 12:08 UTC, merged