lab2 + lab3
ISUCT/Informatics_2023 pull request #140
Opened 2023-11-05 15:23 UTC by Scorp-From-Ivan0v0

2023-11-11 08:02 UTC, jskonst commented on golang/main.go
> +func Primer() {
ее надо разбиать на несколько функций

2023-11-11 08:10 UTC, jskonst requested changes

2023-11-11 08:10 UTC, jskonst commented on golang/main.go
> +	for x <= xk {
```suggestion
	for x:=xn; x <= xk; x+= deltaX {
```

2023-11-11 08:11 UTC, Greenprize commented on golang/main.go
> +	for x <= xk {
![image](https://github.com/ISUCT/Informatics_2023/assets/71152598/3feda19e-863d-418c-842f-4a247c43aadf)

2023-11-11 08:52 UTC, Scorp-From-Ivan0v0 commented on golang/main.go
> +func Primer() {
То есть мне весь пример переделывать что ли? Я думал, раз через одну функцию работает, то так можно оставить

2023-11-11 09:05 UTC, jskonst commented on golang/main.go
> +func Primer() {
ну как бы 3-ю засчитываем, но считайте что пришла 4-я лаба :)

2023-12-02 07:36 UTC, jskonst requested changes

2023-12-02 07:36 UTC, jskonst commented on golang/internal/lab4.go
> +		formattedResult := fmt.Sprintf("%.3f", result)
Разделяем на функции - для задачи А и задачи Б

2023-12-08 19:46 UTC, jskonst requested changes

2023-12-08 19:46 UTC, jskonst commented on golang/main.go
> +	}
это в задачу 2 выносите

2023-12-08 19:46 UTC, jskonst commented on golang/internal/lab4.go
> +	x := xn
это становится параметрами функций

2023-12-08 19:46 UTC, jskonst commented on golang/internal/lab4.go
> +	b := 1.1
это параметры функций

2023-12-08 19:46 UTC, jskonst commented on golang/internal/lab4.go
> +	result := make([]float64, len(values))
а могли бы cap указать...

2023-12-08 19:46 UTC, jskonst commented on golang/internal/lab4.go
> +	e := 2.71828
в math есть math.exp(число) - которая e возведет в степень, соответствующую числу

2023-12-22 22:12 UTC, jskonst requested changes

2023-12-22 22:12 UTC, jskonst commented on golang/internal/Lab4/lab4.go
> +	x := xn
это должно стать параметром функции

2023-12-23 11:58 UTC, jskonst approved these changes

2023-12-23 11:58 UTC, merged