lab 2,3
ISUCT/Informatics_2023 pull request #146
Opened 2023-11-05 19:44 UTC by Vladislav-Bystrov

2023-11-11 07:37 UTC, jskonst commented on lab.go
> +package main
не может быть 2х main (а у вас тут прям сразу 3)

2023-11-11 07:38 UTC, jskonst requested changes

2023-11-11 07:38 UTC, jskonst commented on lab.go
> +package main
оставляйте только 1 файл

2023-12-02 09:46 UTC, Vladislav-Bystrov commented
Переделал лабы 2 и 3

2023-12-08 19:55 UTC, jskonst approved these changes

2023-12-08 19:55 UTC, jskonst commented on golang/main.go
> +const xStep float64 = 0.3
внесли б их в main (но если лни уж колнстанты - ладно)

2023-12-08 19:55 UTC, merged