lab2 + lab3
ISUCT/Informatics_2023 pull request #147
Opened 2023-11-05 20:31 UTC by Vladislav3707

2023-11-11 07:36 UTC, jskonst requested changes

2023-11-11 07:36 UTC, jskonst commented on golang/main.go
> +
не не - переменных вне функций (глобальных) не должно быть

2023-11-11 07:53 UTC, jskonst commented on golang/main.go
> +
![изображение](https://github.com/ISUCT/Informatics_2023/assets/970835/f77dafd2-846a-4ab0-9eb5-cfa3b0243fc7)

2023-12-08 19:57 UTC, jskonst requested changes

2023-12-08 19:57 UTC, jskonst commented on golang/internal/lab4/lab4.go
> +	var results []float64
mke...

2023-12-08 19:57 UTC, jskonst commented on golang/internal/lab4/lab4.go
> +		xn += deltaX
это лучше в самом объявлении цикла делайте

2023-12-08 19:57 UTC, jskonst commented on golang/internal/lab4/lab4.go
> +	}
а тут возвращаемое значение?

2023-12-16 07:31 UTC, Greenprize commented on golang/main.go
> +	fmt.Println(myslicefortask2)
![image](https://github.com/ISUCT/Informatics_2023/assets/71152598/8f19a0b3-cc52-417f-ac35-d02ebd956881)

2023-12-16 07:34 UTC, jskonst requested changes

2023-12-16 07:34 UTC, jskonst commented on golang/internal/lab4/lab4.go
> +	results := make([]float64, 0)
укажите cap чтобы не пересоздавать 
```suggestion
	results := make([]float64, 0, (xk-xn)/deltaX + 1)
```

2023-12-16 07:34 UTC, jskonst commented on golang/main.go
> +	results := lab4.Primer1(0.26, 0.66, 0.08)
```suggestion
	fmt.Println(lab4.Primer1(0.26, 0.66, 0.08))
```

2023-12-16 07:34 UTC, jskonst commented on golang/main.go
> +	results := lab4.Primer1(0.26, 0.66, 0.08)
а можно сделать вывод вида:
x = 0 y = 1
x = 5 y = 7

2023-12-16 07:34 UTC, jskonst commented on golang/internal/lab4/lab4.go
> +func Primer2(myslicefortask2 []float64) []float64 {
не надо мутировать исходный массив

2023-12-23 08:26 UTC, jskonst approved these changes

2023-12-23 08:26 UTC, merged