first lab
ISUCT/Informatics_2023 pull request #157
Opened 2023-11-06 18:23 UTC by AD-sudo-world

2023-11-11 06:51 UTC, jskonst commented on golang/main.go
> +	fmt.Printf("\n")
```suggestion
	fmt.Prinln()
```

2023-11-11 06:54 UTC, jskonst requested changes
В целом хорошо, но нужно переделать на получение параметров функцией и возвращение значений

2023-11-11 06:54 UTC, jskonst commented on golang/main.go
> +	xEnd := 3.7
Параметры a, delta - передавайте в качестве параметров в функцию

2023-11-11 06:54 UTC, jskonst commented on golang/main.go
> +		fmt.Printf("x = %.2f, y = %.2f\n", x, y)
Не выводите, а возвращайте значения из функции - вывод в другом месте (этот Printf можно оставить, но return точно стоит добавить

2023-11-11 06:54 UTC, jskonst commented on golang/main.go
> +	xValues := []float64{1.28, 1.36, 2.47, 3.68, 4.56}
аналогично срез значений передавайте извне

2023-12-15 08:38 UTC, AD-sudo-world commented
хорошо, поправлю

2025-06-07 05:16 UTC, closed without merging