lab3
ISUCT/Informatics_2023 pull request #164
Opened 2023-11-11 13:00 UTC by LysovDmitri

2023-11-12 08:31 UTC, jskonst commented on golang/main.go
> +	return (math.Pow(1.6, (math.Pow(x, 2)-1)) - math.Log10(math.Pow(x, 2)-1) + math.Cbrt((math.Pow(x, 2) - 1)))
а какой вариант? тут есть подозрительно напоминающие а и b константы

2023-11-12 08:32 UTC, jskonst commented on golang/main.go
> +	}
вот это уже можно выносить в отдельную функцию

2023-11-12 08:32 UTC, jskonst requested changes
нужен нормер задания - чтобы посмотреть, в остальном все похоже, но начинайте дальше делать

2023-11-12 14:14 UTC, LysovDmitri commented on golang/main.go
> +	return (math.Pow(1.6, (math.Pow(x, 2)-1)) - math.Log10(math.Pow(x, 2)-1) + math.Cbrt((math.Pow(x, 2) - 1)))
12 вариант

2023-11-16 13:08 UTC, LysovDmitri commented
Здраствуйте, не работает запрос функции из пакета, не могу понять как исправить

2023-11-18 08:45 UTC, jskonst requested changes

2023-11-18 08:45 UTC, jskonst commented on golang/main.go
> +	lab4 "command-line-argumentsC:\\Users\\dmitr\\Desktop\\репризиторий\\Informatics_2023\\golang\\internal\\lab 4\\calculate.go"
воу воу не надо такого

2023-11-18 08:45 UTC, jskonst commented on golang/main.go
> +	}
выносите в отдельный пакет и отдельные функции для задач А и Б

2023-11-18 08:45 UTC, jskonst commented on golang/main.go
> +	}
выносите в отдельный пакет и отдельные функции для задач А и Б

2023-11-19 05:43 UTC, jskonst requested changes

2023-11-19 05:43 UTC, jskonst commented on golang/internal/lab4/calculate.go
> +	x := []float64{}
используйте make - чтобы предварительно выделить под срез нужную емкость и не пересоздавать массив

2023-11-23 15:20 UTC, closed without merging