lab3 var12
ISUCT/Informatics_2023 pull request #168
Opened 2023-11-13 18:46 UTC by J0es1ick

2023-11-18 09:00 UTC, jskonst requested changes

2023-11-18 09:00 UTC, jskonst commented on golang/lab3/lab3.go
> +  	y := []float64{}
посчитайте заранее размер среза и через make создайте нужной емкости

2023-11-18 09:00 UTC, jskonst commented on golang/lab3/lab3.go
> +  	y := []float64{}
аналогично про срез

2023-11-18 09:00 UTC, jskonst commented on golang/lab3/lab3.go
> +    	y = append(y, result(a, x))
что-то с выравниванием не так

2023-11-18 19:03 UTC, J0es1ick commented on golang/lab3/lab3.go
> +  	y := []float64{}
Посчитать самостоятельно или в самой программе?

2023-11-19 05:43 UTC, jskonst requested changes

2023-11-19 05:43 UTC, jskonst commented on golang/lab3/lab3.go
> +  	y := []float64{}
в программе конечно - xn xk dx могут же меняться

2023-12-02 05:21 UTC, jskonst approved these changes

2023-12-02 05:21 UTC, merged