Added structure and its methods
ISUCT/Informatics_2023 pull request #181
Opened 2023-11-26 16:39 UTC by avinogrado

2023-12-02 00:29 UTC, jskonst commented
У вас конфликты с целевой веткой - давайте уже как-то решать, а то я просто закрою этот PR не засчитав

2023-12-02 00:32 UTC, jskonst requested changes

2023-12-02 00:32 UTC, jskonst commented on golang/internal/sample.go
> +type Car struct {
вот это точно из этого файла и из этого пакета, а по хорошему - пока не зайдет функция - это не надо прикладывать

2023-12-02 00:32 UTC, jskonst commented on golang/internal/sample.go
> +type Car struct {
а вот функция бы могла зайти... но сейчас завести не могу - есть лишний код - его выносите в отдельный пакет

2023-12-02 00:32 UTC, jskonst commented on golang/internal/sample.go
> +	return changes
а надо ли его возвращать? фактически у вашей структуры не произойдет изменения цвета

2023-12-02 05:30 UTC, avinogrado commented on golang/internal/sample.go
> +type Car struct {
> вот это точно из этого файла и из этого пакета, а по хорошему - пока не зайдет функция - это не надо прикладывать

Так у меня PR с функцией вы закрывали, я вот и не знаю откуда конфликт

2023-12-02 05:48 UTC, avinogrado commented on golang/internal/sample.go
> +type Car struct {
> а вот функция бы могла зайти... но сейчас завести не могу - есть лишний код - его выносите в отдельный пакет

Я хотел в отдельный пакет изначально это все вынести, но при попытке создать и импортировать этот пакет в main мне компилятор писал, что этот пакет не поддерживается воркспейсом

2023-12-02 07:35 UTC, jskonst commented on golang/internal/car/car.go
> +	fmt.Printf("The car is moving at a speed of %f Kilometers per hour \n", car.MaxSpeedKMPH)
ну тут еще можете Name выводить и color....

2023-12-23 12:04 UTC, jskonst approved these changes

2023-12-23 12:04 UTC, merged