Lab1 + Lab2 + Lab3
ISUCT/Informatics_2023 pull request #186
Opened 2023-11-29 12:00 UTC by Latokes

2023-12-02 00:16 UTC, jskonst requested changes

2023-12-02 00:16 UTC, jskonst commented on golang/main.go
> +}
выносите в отдельный пакет

2023-12-02 00:16 UTC, jskonst commented on golang/main.go
> +	}
выносите в отдельные функции в отдельном пакете

2023-12-02 12:19 UTC, Latokes commented
Вынес в отдельные функции в отдельный пакет.

2023-12-08 20:04 UTC, jskonst reviewed
придется еще пересматривать - а были бы только функции - зачел бы

2023-12-08 20:04 UTC, jskonst commented on .vscode/launch.json
> +{
этот файл удаляйте

2023-12-08 20:04 UTC, jskonst commented on golang/internal/airplanestruct/airplanestruct.go
> +type airplane struct {
этот файл рано - пока не зайдут функции

2023-12-09 11:57 UTC, Latokes commented
Удалил всё, что относится к 5 лабораторной работе

2023-12-09 12:05 UTC, jskonst approved these changes

2023-12-09 12:05 UTC, merged