laba 5
ISUCT/Informatics_2023 pull request #187
Opened 2023-11-29 15:28 UTC by temawan2gecko

2023-12-02 00:08 UTC, jskonst requested changes

2023-12-02 00:08 UTC, jskonst commented on golang/internal/structCat/structCat.go
> +func NewCat(setAge int, setGender, setBreed, setName string) cat {
AssignAge надо вызвать в этом методе - иначе можно создать структуру с отрицательными значениями

2023-12-02 00:08 UTC, jskonst commented on golang/internal/structCat/structCat.go
> +	return fmt.Errorf("I'm afraid there's no cat")
немного оффтоп, но есть возможность создавать отдельные ошибки и выбрасывать их - так легче проверять

2023-12-02 00:08 UTC, jskonst commented on golang/main.go
> +}
лучше все же явно проверить

2023-12-09 07:17 UTC, Greenprize commented
![image](https://github.com/ISUCT/Informatics_2023/assets/71152598/d8b6d926-b51a-431f-9578-8c49f4557b98)

2023-12-23 12:00 UTC, jskonst approved these changes

2023-12-23 12:00 UTC, merged