lab4 + lab5
ISUCT/Informatics_2023 pull request #192
Opened 2023-12-01 19:32 UTC by KochetovDanilRomanovich

2023-12-01 23:36 UTC, jskonst requested changes

2023-12-01 23:36 UTC, jskonst commented on golang/internal/lab4/lab4.go
> +	list_answers := make([]float64, 0)
длину надо указать

2023-12-01 23:36 UTC, jskonst commented on golang/internal/lab4/lab4.go
> +	list_answers := make([]float64, 0)
тут тоже - чтобы не пересоздавать массив под срез

2023-12-01 23:36 UTC, jskonst commented on golang/internal/lab5/lab5.go
> +package lab5
это по идее надо откатывать - предыдущие лабы еще не зашли

2023-12-01 23:36 UTC, jskonst commented on golang/internal/lab5/lab5.go
> +func The_Table(table_lenght, table_widht, table_height float64) table {
получается я могу создать структуру с отрицательной длиной шириной и высотой

2023-12-09 07:11 UTC, Greenprize commented
![image](https://github.com/ISUCT/Informatics_2023/assets/71152598/8d4b2b79-56a7-45f4-beb7-da7d38aeb0e6)

2023-12-09 07:13 UTC, jskonst approved these changes

2023-12-09 07:13 UTC, merged