Lab 3 and Lab 4
ISUCT/Informatics_2023 pull request #200
Opened 2023-12-02 09:34 UTC by MurKote

2023-12-02 11:40 UTC, MurKote commented
Надо посмотреть Lab 3 и Lab 4 ( Add Output )

2023-12-23 12:16 UTC, jskonst requested changes

2023-12-23 12:16 UTC, jskonst commented on golang/internal/lab4/lab4.go
> +func TaskB(numbers [5]float64) []float64 {
передавайте не массив уже а срез

2023-12-24 00:10 UTC, jskonst approved these changes

2023-12-24 00:10 UTC, merged