lab5
ISUCT/Informatics_2023 pull request #247
Opened 2023-12-15 15:59 UTC by RenatZhappuev

2023-12-16 07:25 UTC, Greenprize commented on golang/internal/lab5/lab5.go
> +	}
![image](https://github.com/ISUCT/Informatics_2023/assets/71152598/d74b7477-1222-4b5c-9c21-f00ed6219bb2)

2023-12-16 07:28 UTC, jskonst requested changes

2023-12-16 07:28 UTC, jskonst commented on golang/internal/lab5/lab5.go
> +	} else {
Лучше разделить отдельно проверки ошибок

2023-12-16 07:28 UTC, jskonst commented on golang/internal/lab5/lab5.go
> +	err1 := tmp.SetAge(age)
```suggestion
	if err1 := tmp.SetAge(age); err != nil {
	....
	}
```

2023-12-16 07:28 UTC, jskonst commented on golang/internal/lab5/lab5.go
> +		return nil, fmt.Errorf("Incorrect age and weight of bunny!")
лучше отдельно создать ошибку (так проще проверять тип)
const ErrIncorrectWeight = errors.New("incorrect weight")

2023-12-23 17:32 UTC, jskonst approved these changes

2023-12-23 17:32 UTC, merged