Поменял фио
ISUCT/Informatics_2023 pull request #28
Opened 2023-09-23 09:57 UTC by BranchyDaddy

сыр

2023-09-23 10:49 UTC, jskonst commented on README.md
> +## Владислав Кувшинов Пармезан
? А правильно Пармезан?

2023-09-24 20:05 UTC, jskonst requested changes

2023-09-24 20:05 UTC, jskonst commented on README.md
> +## Владислав Кувшинов Пармезан
вопрос еще открыт

2023-09-25 16:46 UTC, jskonst commented
> сыр

как хотите, но именно так и буду искать в ведомости :)

2023-09-26 11:40 UTC, merged

2023-09-27 07:37 UTC, BranchyDaddy commented
Здравствуйте, я поменяю

вт, 26 сент. 2023 г., 14:40 Eugeny Konstantinov ***@***.***>:

> Merged #28 <https://github.com/ISUCT/Informatics_2023/pull/28> into
> Kuvshinov_Vladislav_Sergeevich.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ISUCT/Informatics_2023/pull/28#event-10473980045>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BCKJ2CKY5VQM5GBDZ77ZZQ3X4K5MJANCNFSM6AAAAAA5ECXG6Q>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>