Update README.md
ISUCT/Informatics_2023 pull request #42
Opened 2023-09-25 19:06 UTC by MarkVRKS

2023-09-26 17:07 UTC, jskonst commented on README.md
> +## Вераксо Марк Владимирович
Все ок - только поменяйте плиз ветку назначения

2023-10-07 05:34 UTC, jskonst commented
@MarkVRKS поменяйте ветку назначения

2023-11-11 08:12 UTC, jskonst commented on golang/math.go
> +		verh := (1 + (math.Sin(b*b*b+x*x*x) * math.Sin(b*b*b+x*x*x)))
1 - вы же создали уже функцию для вычисления в 1 точке? используйте ее

2023-11-11 08:13 UTC, jskonst requested changes

2023-11-11 08:13 UTC, jskonst commented on golang/math.go
> +		fmt.Println("(Задача А)Результат первой формулы из таблицы - ", result)
начинаем выносить в отдельную функцию

2023-11-11 08:14 UTC, Greenprize commented on golang/math.go
> +	fmt.Println("(Задача В)Результат формулы при [x5 = 3.9]  - ", result5)
![image](https://github.com/ISUCT/Informatics_2023/assets/71152598/8449c55c-d455-4cb2-8816-1fde6570ae0a)

2023-11-11 19:45 UTC, jskonst commented on golang/MathInGo.go
> +package MathInGo
перенесите в другой каталог

2023-11-18 08:21 UTC, jskonst requested changes

2023-11-18 08:21 UTC, jskonst commented on golang/math2
> +package main
вот этот надо удалять

2023-11-18 08:21 UTC, jskonst commented on golang/math.go
> +package main
выносите в отдельный пакет и разбивайте на функции

2023-11-18 08:21 UTC, jskonst commented on golang/MathInGo.go
> +package MathInGo
в каталоге internal

2023-11-25 16:07 UTC, jskonst commented on golang/main.go
> +	ДОДЕЛАТЬ
хм - вот тут линтер должен просто все красным окарасить

2023-11-25 16:08 UTC, jskonst commented
Удалите лишнее - если есть вопросы - напишите

2023-12-01 20:42 UTC, jskonst requested changes

2023-12-01 20:42 UTC, jskonst commented on golang/internal/cat_1_variant
> +package internal
не надо его в принципе пока размещать в репозитории - можете у себя локально на отдельной ветке

2023-12-01 20:42 UTC, jskonst commented on golang/internal/sample.go
> +	fmt.Println(funktion1(x1))
для задачи B нужно передать срез на вход в качестве параметров

2023-12-01 20:42 UTC, jskonst commented on golang/internal/sample.go
> +	}
вот это надо вынести в отдельную функцию

2023-12-01 20:42 UTC, jskonst commented on golang/math.go
> +package main
кдалите уже этот файлик :)

2023-12-03 09:57 UTC, MarkVRKS commented on golang/internal/sample.go
> +	}
Именно цикл надо представить в видео функции?

2023-12-08 19:20 UTC, jskonst requested changes

2023-12-08 19:20 UTC, jskonst commented on golang/internal/cat_1_var.go
> +}
вот с котами рановато начали

2023-12-08 19:20 UTC, jskonst commented on golang/internal/sample.go
> +	var valuefnk = []float64{}
используйте make для выделения под срезом массива нужного размера

2023-12-08 19:20 UTC, jskonst commented on golang/internal/sample.go
> +	var valuefnk = []float64{}
вы же можете посчитать - (xk-xn)/ds +1 - примерно так

2023-12-08 19:20 UTC, jskonst commented on golang/internal/cat_1_var.go
> +}
ну и простая рекомендация - выносите в отдельный пакет - потом увидите проблемы :) и зачем методы в том числе нужны

2023-12-16 09:04 UTC, jskonst requested changes

2023-12-16 09:04 UTC, jskonst commented on golang/internal/lab5/cat1.go
> +func main() {
да не может быть 2х main....

2023-12-22 20:53 UTC, jskonst commented on golang/internal/lab5/cat1.go
> +    colour string
а что с выравниванием?

2023-12-22 20:54 UTC, jskonst requested changes

2023-12-22 20:54 UTC, jskonst commented on golang/main.go
> +	answer1 := internal.Cycle(1.28, 3.28, 0.4)
вот тут пример с использованием структуры кота пожалуйста

2023-12-22 20:58 UTC, jskonst commented
ну и линтеры еще упали

2023-12-23 11:56 UTC, merged