dobavil fio
ISUCT/Informatics_2023 pull request #62
Opened 2023-10-02 17:01 UTC by gureviv

2023-10-07 06:08 UTC, jskonst requested changes

2023-10-07 06:08 UTC, jskonst commented on README.md
> +## ФИО 111  1
? а почему так - пернесите фио сюда, а 111 - удалите

2023-11-11 19:52 UTC, jskonst commented on golang/main.go
> +	fmt.Println("Задача B")
Это уже можно переносить в отдельные функции

2023-11-11 19:53 UTC, jskonst commented on golang/main.go
> +	for x < 5 {
а почему < 5 ?

2023-11-11 19:53 UTC, jskonst commented on golang/main.go
> +	for x < 5 {
но эти исправления после того, как вы перенесете в отдельную функцию

2023-11-12 11:31 UTC, gureviv commented on golang/main.go
> +	fmt.Println("Задача B")
Хорошо

2023-11-12 11:31 UTC, gureviv commented on golang/main.go
> +	for x < 5 {
> а почему < 5 ?

"<5" потому что 5 не нужна, т.к. x используется как  индекс list_of_x, а элементов там 5 и значит индексы от 0 до 4.

2023-11-12 18:34 UTC, jskonst commented on golang/main.go
> +	return y
```suggestion
	x = math.Round(math.Abs(x)*100) / 100
	if x < 1 {
		return math.Acos(x)
	} 
	return  math.Pow(1.2, x) - math.Pow(x, 1.2)
```

2023-11-12 18:36 UTC, jskonst requested changes

2023-11-12 18:36 UTC, jskonst commented on golang/main.go
> +	for x < 5 {
я не про это, а про то - что вы тут жестко привязаны к 5 - начинайте делать следующую работу - разбивать на функции

2023-11-12 18:40 UTC, gureviv commented on golang/main.go
> +	for x < 5 {
Хорошо

2023-11-25 16:05 UTC, jskonst requested changes

2023-11-25 16:05 UTC, jskonst commented on golang/internal/lab4/lab4.go
> +	var list_of_y = []float64{}
вот тут бы make использовать - для примерного вычисления размера требуемого размера у среза

2023-11-25 16:05 UTC, jskonst commented on golang/main.go
> +	xA, yA = lab4.TaskA(0.2, 2.2, 0.4)
```suggestion
	xA, yA := lab4.TaskA(0.2, 2.2, 0.4)
```

2023-11-25 16:05 UTC, jskonst commented on golang/main.go
> +	for i < len(xA) {
исользуйте range

2023-11-25 16:05 UTC, jskonst commented on golang/main.go
> +	for j < len(xB) {
аналогично используйте range

2023-11-25 16:05 UTC, jskonst commented on golang/internal/lab4/lab4.go
> +	for i < len(a) {
используйте range

2023-12-08 19:17 UTC, jskonst approved these changes

2023-12-08 19:17 UTC, jskonst commented on golang/internal/lab4/lab4.go
> +	// var list_of_y = []float64{}
закомментированный код - удаляйте или помечайте почему он вам не нужен

2023-12-08 19:17 UTC, merged

2023-12-08 19:29 UTC, gureviv commented on golang/internal/lab4/lab4.go
> +	// var list_of_y = []float64{}
извиняюсь - забыл убрать