changed main.go
ISUCT/Informatics_2023 pull request #80
Opened 2023-10-07 11:09 UTC by sweetfyx

2023-11-11 20:34 UTC, jskonst commented on golang/main.go
> +	var answersA = []float64{}
прикиньте размер и через make заранее создайте примерного размера чтобы при append не слишком часто пересоздавать массив

2023-11-11 20:36 UTC, jskonst requested changes

2023-11-11 20:36 UTC, jskonst commented on golang/main.go
> +	fmt.Println(answersA)
не выводите на экран, а возвращайте значения

2023-11-11 20:36 UTC, jskonst commented on golang/main.go
> +	var znachX = []float64{x1, x2, x3, x4, x5}
не не - передавайте как раз срез в качестве параметров функции

2023-11-26 09:30 UTC, sweetfyx commented on golang/main.go
> +	var znachX = []float64{x1, x2, x3, x4, x5}
постарался пофиксить все комменты, проверьте пожалуйста

2023-12-01 20:46 UTC, jskonst requested changes

2023-12-01 20:46 UTC, jskonst commented on golang/main.go
> +func task1(a float64, b float64, x1 float64, x2 float64, deltax float64) []float64 {
Выносите в отдельный пакет

2023-12-01 20:46 UTC, jskonst commented on golang/main.go
> +	answersA := make([]float64, 0, 10)
а почему 10? вы же можете посчитать

2023-12-01 20:46 UTC, jskonst commented on golang/main.go
> +	answersB := make([]float64, 0, 10)
а тут то длину вы в принципе можете легко получить из len(xValues)

2023-12-02 05:52 UTC, sweetfyx commented on golang/main.go
> +	answersB := make([]float64, 0, 10)
исправил, проверьте пожалуйста

2023-12-02 07:41 UTC, jskonst requested changes

2023-12-02 07:41 UTC, jskonst commented on golang/internal/lab4/lab4.go
> +		var y float64 = math.Sqrt((math.Abs(a - b*x)) / (math.Pow(math.Log10(x), 3)))
у вас код на 10 и 18 продублирован - выносите в отдеьную функцию

2023-12-02 08:58 UTC, sweetfyx commented on golang/internal/lab4/lab4.go
> +		var y float64 = math.Sqrt((math.Abs(a - b*x)) / (math.Pow(math.Log10(x), 3)))
пофиксил

2023-12-08 19:23 UTC, jskonst approved these changes

2023-12-08 19:23 UTC, merged