Calculation func`s lab after unnecessary conversion fix
ISUCT/Informatics_2023 pull request #86
Opened 2023-10-07 21:39 UTC by avinogrado

2023-11-11 08:19 UTC, jskonst commented on golang/internal/sample.go
> +
лишние пустые строки не особо нужны

2023-11-11 08:19 UTC, jskonst commented on golang/internal/sample.go
> +	}
вот эту задачу надо выносить в отдельную функцию

2023-11-11 08:19 UTC, jskonst commented on golang/internal/sample.go
> +	}
эту тоже надо в отдельную функцию выносить

2023-11-11 08:20 UTC, jskonst commented on golang/internal/sample.go
> +	}
только эта функция должна на вход получать xn, xk, dx (a и b тоже)

2023-11-11 08:21 UTC, jskonst commented on golang/internal/sample.go
> +	for i := 0; i <= len(numbers)-1; i++ {
```suggestion
	for _, val = range numbers {
```

2023-11-11 08:21 UTC, jskonst requested changes
можно уже расносить на несколько функций

2023-11-11 08:22 UTC, Greenprize commented on golang/internal/sample.go
> +	}
![image](https://github.com/ISUCT/Informatics_2023/assets/71152598/4974de9b-1cb4-413d-98db-36c6dd0d2f08)

2023-11-11 08:34 UTC, avinogrado commented on golang/internal/sample.go
> +	}
> только эта функция должна на вход получать xn, xk, dx (a и b тоже)

В моей задаче нет A и B, поэтому я их и не задаю

2023-11-12 07:49 UTC, jskonst commented on golang/tests/sample_test.go
> +		t.Fatalf(` Func_resolution(1) = %v, want 1.1066819197003217, error`, resol)
можно, но можно упростить используя testify

2023-11-12 08:05 UTC, jskonst commented on golang/tests/sample_test.go
> +	if resol != 1.1066819197003217 {
округляйте, иначе из-за проблем с округлением получится что при одном из запусков окажется есть расхождение в самом последнем знаке

2023-11-12 08:06 UTC, jskonst commented on golang/tests/sample_test.go
> +func Test_fu(t *testing.T) {
добавьте еще тестов на критическаие точки (если таковые есть)

2023-11-12 08:07 UTC, jskonst commented on golang/internal/sample.go
> +func Func_resolution(x float64) float64 {
не используйте snace_case - в go все же CamelCase

2023-11-12 08:07 UTC, jskonst commented on golang/internal/sample.go
> +	root4 := math.Pow(mod, float64(1)/float64(4))
```suggestion
	root4 := math.Pow(mod, 1/4.0)
```

2023-11-12 08:07 UTC, jskonst commented on golang/internal/sample.go
> +func Massive(numbers [5]float64) []float64 {
```suggestion
func Massive(numbers []float64) []float64 {
```
все же переезжаем на срезы

2023-11-12 08:08 UTC, jskonst commented on golang/internal/sample.go
> +	var numbers_massive = []float64{}
```suggestion
	var numbers_massive = make([]float64, 0, len(numbers)) 
```
тогда не будет происходить несколько раз выделения нового массива под срез

2023-11-12 08:09 UTC, jskonst requested changes
Можно чуть улучшить, но в целом уже почти то что нужно

2023-11-25 16:11 UTC, jskonst commented on golang/tests/sample_test.go
> +	assert.InDelta(t, 1.1066819197003217, resol, 0.02)
Так то оставим: но в целом тестов должно быть сильно больше - и на задачу A и на задачу B

2023-11-25 16:14 UTC, jskonst requested changes

2023-11-25 16:14 UTC, jskonst commented on golang/internal/sample.go
> +	var numbers_cycle = []float64{}
используйте make для того, чтобы не пересоздавать слишком часто нижележащий в срезе массив

2023-11-25 16:14 UTC, jskonst commented on golang/internal/sample.go
> +	var numbers_cycle = []float64{}
вы же +- можете прикинуть сколько вам нужно элементов

2023-11-25 16:56 UTC, avinogrado commented on golang/internal/sample.go
> +	var numbers_cycle = []float64{}
А если посчитать полностью сколько будет итераций, то можно просто задать массив через [n]float64?

2023-11-25 17:31 UTC, jskonst commented on golang/internal/sample.go
> +	var numbers_cycle = []float64{}
а вот попробуйте - не выйдет - для массива вы должны в параметрох функции в возвращаемых значениях точное число указать

2023-11-25 17:31 UTC, jskonst approved these changes

2023-11-25 17:32 UTC, merged